---
- name: Set up the Debian unstable repository
  become: true
  debconf:
    name: "APT::Default-Release"
    value: "unstable"
    vtype: "select"

- name: Pin Debian stable packages
  become: true
  apt_preferences:
    name: "Pin Debian stable packages"
    package: "*"
    pin: "release a=stable"
    priority: "900"
    filename: /etc/apt/preferences.d/pin_stable

- name: Pin Debian unstable packages
  become: true
  apt_preferences:
    name: "Pin Debian unstable packages"
    package: "*"
    pin: "release a=unstable"
    priority: "10"
    filename: /etc/apt/preferences.d/pin_unstable
  
- name: Update package information
  become: true
  apt:
    update_cache: yes
