---
- hosts: digi_tree_monitor
  become: true

  pre_tasks:
    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.example.yml

    - name: Ensure apt cache is up to date.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml

    - name: Set up Internet Monitoring.
      ansible.builtin.import_tasks: tasks/internet-monitoring.yml
      when: monitoring_enable

    - name: Set up Pi Hole.
      ansible.builtin.import_tasks: tasks/pi-hole.yml
      when: pihole_enable

    - name: Set up Shelly Plug Monitoring.
      ansible.builtin.import_tasks: tasks/shelly-plug.yml
      when: shelly_plug_enable

    - name: Set up Air Gradient Monitoring.
      ansible.builtin.import_tasks: tasks/airgradient.yml
      when: airgradient_enable

    - name: Set up Starlink Monitoring.
      ansible.builtin.import_tasks: tasks/starlink.yml
      when: starlink_enable

- name: Set up cluster-wide configuration.
  hosts: cluster
  gather_facts: false
  become: true

  handlers:
    - name: reboot-pi
      reboot:

  vars_files:
    - config.yml

  tasks: []


- name: Configure the control plane (node 1).
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - config.yml

  tasks:
    # See: https://forums.raspberrypi.com/viewtopic.php?t=274486
    - name: Set up the Debian unstable repo.
      ansible.builtin.import_tasks: tasks/set_up_debian_unstable_repo.yml
      when: unstable_debian_enable

    # See: https://ceph.com/en/news/blog/2022/install-ceph-in-a-raspberrypi-4-cluster/
    - name: Install cephadm.
      ansible.builtin.package:
        name: cephadm
        state: present

    - name: Create the ceph cluster
      become: true
      command: cephadm bootstrap --mon-ip {{ mon_ip }}
      register: ceph_cluster_creation
      changed_when: ceph_cluster_creation.rc != 0
      notify:
        - reboot-pi

    - name: Retrieve the ceph pubkey.
      ansible.builtin.fetch:
        src: /etc/ceph/ceph.pub
        dest: files/ceph.pub
        flat: yes

    - name: Ensure NFS dependencies are installed.
      ansible.builtin.package:
        name:
          - libcephfs2
          - nfs-ganesha
          - nfs-ganesha-ceph
        state: present